# -*- coding: utf-8 -*-
"""Digital Botanist

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iRrR3B18i9qyYkGCdRPDGh58VvEC1Hfb
"""

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# st.set_page_config(
#     page_title="Digital Botanist",
#     page_icon="🌿",
#     layout="wide"
# )
# 
# st.title("🌿 Digital Botanist")
# st.subheader("AI-Based Plant Disease Detection")
# 
# st.write(
#     "Upload an image of a plant leaf to analyze its health "
#     "and identify possible diseases."
# )
# 
# st.divider()
# 
# st.header("🔬 Leaf Analysis")
# 
# uploaded_file = st.file_uploader(
#     "Upload a leaf image",
#     type=["jpg", "jpeg", "png"]
# )
# 
# if uploaded_file is not None:
#     st.image(
#         uploaded_file,
#         caption="Uploaded Leaf",
#         width=400
#     )
# 
#     if st.button("🔍 Analyze Leaf"):
#         st.info("AI analysis will be connected in the next steps.")
# 
# st.divider()
# 
# st.caption("Digital Botanist — Biology + Artificial Intelligence Research Project")

!npm install -g localtunnel

!streamlit run app.py &>/content/logs.txt & npx localtunnel --port 8501

!streamlit run app.py --server.port 8501

!pip install -q pyngrok

import subprocess
import time

process = subprocess.Popen(
    ["streamlit", "run", "app.py", "--server.port", "8501"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

time.sleep(5)

print("Digital Botanist is running.")

from pyngrok import ngrok

public_url = ngrok.connect(8501)

print("Your Digital Botanist website:")
print(public_url)

!npx localtunnel --port 8501 > /content/tunnel.txt 2>&1 &

!cat /content/tunnel.txt